DROP TABLE IF EXISTS sports_bars CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
  id BIGSERIAL PRIMARY KEY,
  email VARCHAR NOT NULL UNIQUE,
  password_digest VARCHAR NOT NULL
);

CREATE TABLE sports_bars (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255),
  address VARCHAR(255),
  rating INT,
  price VARCHAR(255),
  icon TEXT,
  lat VARCHAR,
  long VARCHAR
);